#!/bin/bash

python3 evaluation.py new_korean_lch_embeddings_vsize300_bsize100_lr001_nn-True3_reg-False_graph_emb.vec.gz Korean_Korlex_dataset/korean_eval/rm_new_korean_simlex_lch.tsv Korean_Korlex_dataset/korean_eval/simlex_synsets/rm_new_korean_max_lch_human.tsv

python3 evaluation.py new_korean_shp_embeddings_vsize300_bsize100_lr001_nn-True3_reg-False_graph_emb.vec.gz Korean_Korlex_dataset/korean_eval/rm_new_korean_simlex_shp.tsv Korean_Korlex_dataset/korean_eval/simlex_synsets/rm_new_korean_max_shp_human.tsv

python3 evaluation.py new_korean_wup_embeddings_vsize300_bsize100_lr001_nn-True3_reg-False_graph_emb.vec.gz Korean_Korlex_dataset/korean_eval/rm_new_korean_simlex_wup.tsv Korean_Korlex_dataset/korean_eval/simlex_synsets/rm_new_korean_max_wup_human.tsv

python3 evaluation.py new_korean_jcn-semcor_embeddings_vsize300_bsize100_lr001_nn-True3_reg-False_graph_emb.vec.gz Korean_Korlex_dataset/korean_eval/rm_new_korean_simlex_jcn-semcor.tsv Korean_Korlex_dataset/korean_eval/simlex_synsets/rm_new_korean_max_jcn-semcor_human.tsv
